### ISSUE TITLE
Generate keys in SessionService using some random generator mechanism

### ISSUE THREAD

**Issue by lealceldeiro** [lealceldeiro/gms#1]
**Is your feature request related to a problem? Please describe.**
As an open source project anyone can get access to the keys hardcoded in client/src/app/core/session/session.service.ts (SessionService#keys.*). This may represent a serious security risk.

**Describe the solution you'd like**
These values should be generated randomly.

**Describe alternatives you've considered**
[`Math.random`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) seems to be a good starting point.

**Additional context**
If there is any utility class that could do the job, that'd be great.

**Comment by mahditakrim** [comment]
Hi @lealceldeiro ,
Two questions : 
first what do those keys doing (SessionService#keys) ?
and why hard coding them causes security risk (want to know the usage of them) ?

**Comment by lealceldeiro** [comment]
Hi, @mahditakrim 
Answering to your questions:

> what do those keys doing (SessionService#keys) ?

Ultimately these keys are used to store session-related information in the browser local storage or in the cookies (i.e.: see [`SessionService#setAuthData`](https://github.com/lealceldeiro/gms/blob/master/client/src/app/core/session/session.service.ts#L182)). This session-related information can be _access|refresh tokens_, some user-specific information, etc. Their particular usage is through the `StorageService`, which provides methods to save any information in the browser storage under a defined key (i.e.: take a look at [`StorageSerice#set`](https://github.com/lealceldeiro/gms/blob/master/client/src/app/core/storage/storage.service.ts#L85).

> why hard coding them causes security risk (want to know the usage of them) ?

If these keys are hardcoded (as they are now) every client using the application will have the mentioned information stored in their browsers under the same keys (under the browser defined storage for the domain where the app is running).

For example if you start the app and two users from different locations do login, we can know that in both user's browsers there will be a key [`gms_ls_`](https://github.com/lealceldeiro/gms/blob/master/client/src/app/core/storage/storage.service.ts#L22)[`lDmj8ddDj83DJ02kdkjDJ0_kdj9Dks9dkD23jCdkj7dfjDJ0Ck`](https://github.com/lealceldeiro/gms/blob/master/client/src/app/core/session/session.service.ts#L36) holding the authentication data. Something like the below image:

![Sample-Info-Stored](https://user-images.githubusercontent.com/15990580/67072639-0438eb80-f18e-11e9-80e3-3d2892d70feb.PNG)

**Additional considerations**:

I'm still thinking what could be the real impact of this. If an attacker gain access to the client's data in the browser s/he may know what to look for exactly.

On the other hand I need to find a way to make these values somehow random, but being able to identify them after the user close the browser and reopen it again (the Angular app is shutdown and loaded again). If the values are randomly generated the app may not be able to identify the previous values and will keep creating new values every time and losing the previously stored information.

**Comment by mahditakrim** [comment]
Dear @lealceldeiro,
First of all thanks for your complete description.
What I figured out so far is that you have some keys (hard coded in SessionService class) and you can read/update the information stored in browser with those keys every time user loges in or etc...
And if an attacker get the keys from the application (maybe as another user), s/he can read/update the information which are stored in browser.

Am I right ?

Questions:
1. Why don't you store the keys in other places (calling them from other places by encryption) ?
2. What is your algorithm of making the keys (if you made them) ?
3. Is that possible to have a bot which can write unique keys in every application (just asking :D) ?
4. What do you mean by randomizing the values (which I think are in json type) ?

**Comment by lealceldeiro** [comment]
> Am I right ?

You're correct about this.

> Questions:
> 
> 1. Why don't you store the keys in other places (calling them from other places by encryption) ?

Yes, this is a correct approach. I'm thinking about setting some [salt](https://en.wikipedia.org/wiki/Salt_(cryptography)) in the corresponding [config.json](https://github.com/lealceldeiro/gms/blob/master/client/src/assets/config/config.prod.json) (recently introduced) and with some idempotent function generate the keys for the `SessionService` class.

> 2. What is your algorithm of making the keys (if you made them) ?

None so far. This project was rather a study case, so I'm trying to getting it in shape now.

> 3. Is that possible to have a bot which can write unique keys in every application (just asking :D) ?

I think it's possible: having a salt configured (this will give the owner of the app the power of changing the output of the generator algorithm) and an idempotent function (as mentioned before). This will generate a unique (or at least with low probability of being the same) key for every application deployed and without losing the data in between application restarts.

> 4. What do you mean by randomizing the values (which I think are in json type) ?

I'm not sure I understand your question. The keys are not in json type, they are part of a typescript class. Anyways, when I say randomize values, I'm talking about generating these keys used to store cookies in a way that from deployed application to deployed application they vary but for a same instance the values remain the same over app restarts (otherwise we would lose the data previously stored since we wouldn't be able to identify previous keys).

PS: I don't have a solid proposition for this yet. Sadly my time for this project is limited.
